const images = {
  cech: require("../Images/cech.png"),
  leno: require("../Images/leno.png"),
  koscielny: require("../Images/koscielny.png"),
  ramsey: require("../Images/ramsey.png"),
  lacazette: require("../Images/lacazette.png"),
  martinez: require("../Images/martinez.png"),
  bellerin: require("../Images/bellerin.png"),
  holding: require("../Images/holding.png"),
  monreal: require("../Images/monreal.png"),
  mustafi: require("../Images/mustafi.png"),
  mavropanos: require("../Images/mavropanos.png"),
  kolasinac: require("../Images/kolasinac.png"),
  lichsteiner: require("../Images/lichsteiner.png"),
  sokratis: require("../Images/sokratis.png"),
  elneny: require("../Images/elneny.png"),
  mkhitaryan: require("../Images/mkhitaryan.png"),
  ozil: require("../Images/ozil.png"),
  iwobi: require("../Images/iwobi.png"),
  maitlandniles: require("../Images/maitlandniles.png"),
  xhaka: require("../Images/xhaka.png"),
  torreira: require("../Images/torreira.png"),
  guendouzi: require("../Images/guendouzi.png"),
  smithrowe: require("../Images/smithrowe.png"),
  willock: require("../Images/willock.png"),
  aubameyang: require("../Images/aubameyang.png"),
  welbeck: require("../Images/welbeck.png"),
  nketiah: require("../Images/nketiah.png")
};
export default images;
